name: Scrape daily fuel moisture maps

on:
  workflow_dispatch:
  schedule:
    - cron: '35 23 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Scrape fuel moisture maps
      run: |-
        YESTERDAY=$(date --date=yesterday +"%Y-%m-%d")
        OUTPUT_US_10_HOUR=$(echo "images/$YESTERDAY-fuel-moisture-us-10h.png")
        curl https://www.wfas.net/images/firedanger/fm_10.png -o $OUTPUT_US_10_HOUR
        OUTPUT_US_100_HOUR=$(echo "images/$YESTERDAY-fuel-moisture-us-100h.png")
        curl https://www.wfas.net/images/firedanger/fm_100.png -o $OUTPUT_US_100_HOUR
        OUTPUT_US_1000_HOUR=$(echo "images/$YESTERDAY-fuel-moisture-us-1000h.png")
        curl https://www.wfas.net/images/firedanger/fm_1000.png -o $OUTPUT_US_1000_HOUR
    - name: Make animations of anomaly-daily
      uses: jruipinto/ImageMagick-action@v1
      with: 
        command: convert -loop 0 images/*-fuel-moisture-us-10h.png fuel-moisture-us-10h.png.gif
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add images/*.png
        git add fuel-moisture-us-10h.png.gif
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
